version : '3'
services:
  node:
    container_name: app 
    build: . 
    ports: 
      - "8080:3000"
    volumes: 
      - ./uploads:/app/uploads
    
  #commande : 
  # etre au bone endroit = dans le dossier docker compose
  # docker compose up -d
  # => fait un reseua le volume et le container 

# docker ps
# docker compose down = stop 
# docker compose down -l 