version : '3'
services:
  mysql-server: 
    container_name: database
    image: mysql 
    env_file:
      - ./env/database.env
    volumes: 
      - app-01-data:/var/lib/mysql
    restart: on-failure
  front-app:
    containner_name: app 
    image: front-app
    build: ./app
    depends_on:
      - mysql-server
    ports: 
      - "8080:3000"
    
volumes: 
  app-01-data: 


  #commande : 
  # etre au bone endroit = dans le dossier docker compose
  # docker compose up -d
  # => fait un reseua le volume et le container 

# docker ps
# docker compose down = stop 
# docker compose down -l 